
- name: assert all vars are set
  assert: { that: "{{ item }} != '' " }
  with_items:
  - installation_folder

- name: stop selenium agent service
  command: "launchctl unload {{ service_plist_file_path }}"
  ignore_errors: yes

- name: remove selenium agent plist
  file: 
    path: "{{ service_plist_file_path }}"
    state: absent

- name: stop other service
  shell: "/bin/kill -9 $(ps -ef | grep {{ item }} | grep -v grep | awk '{print $2}' | xargs)"
  with_items:
    - selenium_agent_server
    - selenium_grid_node
    - manual.*.jar
    - watch
    - safaridriver
  become: yes
  changed_when: no
  failed_when: no
  ignore_errors: yes

- name: remove installation folder
  file:
    path: "{{ installation_folder }}"
    state: absent
  become: yes
