

# validation

- name: assert all vars are set
  assert: { that: "{{ item }} != '' " }
  with_items:
    - autologin_pass

- name: tap to kcpassword
  homebrew_tap:
    name:  xfreebird/utils

- name: install kcpassword
  homebrew:
    name:  kcpassword

- name: run the autologin util
  command: enable_autologin "{{ autologin_user | default(ansible_user_id) }}" "{{ autologin_pass }}"

- name: reboot the machine
  reboot:
    reboot_timeout: "{{ reboot_timeout | default(600) }}"
  
  become: yes
  when:
    - avoid_reboot | default('yes') | bool
