
- name: assert all vars are set
  assert: { that: "{{ item }} != '' " }
  with_items:
  - installation_folder
  - temp_folder

- name: stop the service
  shell: "/bin/kill -9 $(ps -ef | grep {{ item }} | grep -v grep | awk '{print $2}' | xargs)"
  with_items:
    - selenium_agent_server
    - selenium_grid_node
    - manual.*.jar
    - watch
    - safaridriver
  become: yes
  ignore_errors: yes

- name: remove installation folder
  file:
    path: "{{ installation_folder }}"
    state: absent
  become: yes
