
- name: assert all vars are set
  assert: { that: "{{ item }} != '' " }
  with_items:
  - installation_folder
  - temp_folder

- name: kill the old service
  win_shell: |
    taskkill /F /IM selenium_agent_server.exe /T
  register: killseleniumresults
  changed_when: killseleniumresults.rc == 0 and 'The process "selenium_agent_server.exe" not found.' not in killseleniumresults.stderr
  failed_when: killseleniumresults.rc != 0 and 'The process "selenium_agent_server.exe" not found.' not in killseleniumresults.stderr
  become: yes
  
- name: remove installation folder
  win_file: 
    path: "{{ installation_folder }}"
    state: absent

- name: remove temp folder
  win_file:
    path: "{{ temp_folder }}"
    state: absent
  when: clear_temp_folder == True
