
# ## need to check if this required ?
# - name: start the service (windows)
#   win_shell: "{{ installation_folder }}\\{{ launcher_file_name }}"
#   ignore_errors: True    
#   become: yes

- name: wait for service to start
  win_health_check:
    url: "http://localhost:{{ health_check_port | default(server_port) }}{{ health_check_uri | default('/manage/info') }}"
    expected_status: "{{ health_check_status | default('200') }}"
    max_retries: "{{ health_check_max_retries | default('20') }}"

- name: get installed version from version.properties file
  slurp:
    src: "{{ installation_folder }}/config/version.properties"
  register: installed_version
  
- name: print installed version
  debug:
    msg: " Installed version: {{ (installed_version['content'] | b64decode).split('=')[1] }}"

- name: fail if app_version is not equal to installed version
  fail:
    msg: "app_version: {{ app_version }} does not macthed to installed version {{ (installed_version['content'] | b64decode).split('=')[1] }}"
  when: app_version != (installed_version['content'] | b64decode).split('=')[1]
